services:
  - type: web
    name: mof-discovery
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DEMO_MODE
        value: "False"
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
