"""
CoRE MOF 2019 curated subset with published adsorption data.

Structural properties: Chung et al., JCTC 2019 (CoRE MOF 2019 database).
Adsorption data: cited per-entry in key_paper field.
null = property not characterized / not found in searched literature.
"""
from __future__ import annotations
from sqlalchemy.orm import Session
from models import MOFStructure

# fmt: off
SEED_MOFS: list[dict] = [

    # =========================================================================
    # WATER HARVESTING — Nobel Prize 2025 application (Yaghi group + others)
    # =========================================================================
    {
        "name": "MOF-801",
        "common_name": "Zr-fumarate",
        "formula": "Zr6O4(OH)4(fumarate)6",
        "topology": "fcu",
        "metal_node": "Zr",
        "linker": "fumaric acid",
        "pore_limiting_diameter_A": 5.5,
        "largest_cavity_diameter_A": 7.4,
        "void_fraction": 0.37,
        "surface_area_m2_g": 990.0,
        "surface_area_m2_cm3": 1237.0,
        "density_g_cm3": 1.25,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.22,
        "water_uptake_g_g_40rh": 0.36,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Kim et al., Science 2017; Furukawa et al., JACS 2014",
        "core_mof_id": "ABAVIJ",
        "notes": "Benchmark atmospheric water harvesting MOF. S-shaped isotherm with step at ~20% RH. Nobel Prize-cited application (Yaghi).",
    },
    {
        "name": "MOF-303",
        "common_name": "Al-PIA",
        "formula": "Al(OH)(pyrazole-3,5-dicarboxylate)",
        "topology": None,
        "metal_node": "Al",
        "linker": "pyrazole-3,5-dicarboxylic acid",
        "pore_limiting_diameter_A": 4.8,
        "largest_cavity_diameter_A": 6.2,
        "void_fraction": 0.35,
        "surface_area_m2_g": 1120.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.48,
        "water_uptake_g_g_40rh": 0.52,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Hanikel et al., Science 2021",
        "core_mof_id": None,
        "notes": "Record water uptake at 20% RH. Al-based, excellent low-humidity AWH performance. Yaghi group.",
    },
    {
        "name": "CAU-23",
        "common_name": "Al-MBM",
        "formula": "Al(OH)(4,4'-methylenedibenzoate)",
        "topology": None,
        "metal_node": "Al",
        "linker": "4,4'-methylenedibenzoic acid",
        "pore_limiting_diameter_A": 5.6,
        "largest_cavity_diameter_A": 7.8,
        "void_fraction": 0.43,
        "surface_area_m2_g": 1350.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.46,
        "water_uptake_g_g_40rh": 0.50,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Lenzen et al., Nature Communications 2019",
        "core_mof_id": None,
        "notes": "High-performance water harvesting at low RH. Al-based for stability and scalability.",
    },
    {
        "name": "Al-fumarate",
        "common_name": "Basolite A520",
        "formula": "Al(OH)(fumarate)",
        "topology": None,
        "metal_node": "Al",
        "linker": "fumaric acid",
        "pore_limiting_diameter_A": 5.2,
        "largest_cavity_diameter_A": 6.8,
        "void_fraction": 0.38,
        "surface_area_m2_g": 1070.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.28,
        "water_uptake_g_g_40rh": 0.35,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Bunzen et al., CrystEngComm 2020; commercial BASF grade",
        "core_mof_id": None,
        "notes": "Commercially available. Scalable synthesis. Used in adsorption chillers.",
    },
    {
        "name": "MIL-100(Al)",
        "common_name": "MIL-100 aluminum trimesate",
        "formula": "Al3(OH)(BTC)2",
        "topology": "mtn",
        "metal_node": "Al",
        "linker": "trimesic acid (BTC)",
        "pore_limiting_diameter_A": 5.5,
        "largest_cavity_diameter_A": 25.0,
        "void_fraction": 0.62,
        "surface_area_m2_g": 2150.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.54,
        "has_open_metal_sites": True,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.12,
        "water_uptake_g_g_40rh": 0.45,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": 3.8,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Akiyama et al., Microporous Mesoporous Mater. 2011; Elsayed et al., Sol. Energy 2017",
        "core_mof_id": "RAVVUH",
        "notes": "Mesoporous Al-MIL-100. Step uptake at 30-40% RH; less effective at 20% RH. Good for moderate-humidity AWH.",
    },
    {
        "name": "MIL-100(Fe)",
        "common_name": "Fe-MIL-100",
        "formula": "Fe3(OH)(BTC)2",
        "topology": "mtn",
        "metal_node": "Fe",
        "linker": "trimesic acid (BTC)",
        "pore_limiting_diameter_A": 5.5,
        "largest_cavity_diameter_A": 25.0,
        "void_fraction": 0.62,
        "surface_area_m2_g": 2000.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.98,
        "has_open_metal_sites": True,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.15,
        "water_uptake_g_g_40rh": 0.50,
        "co2_uptake_mmol_g_015bar": 1.9,
        "co2_uptake_mmol_g_1bar": 3.5,
        "co2_n2_selectivity": 12.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Henninger et al., EJIC 2012; Wack et al., CrystEngComm 2013",
        "core_mof_id": "XEGKUR",
        "notes": "Iron-based MIL-100. Mesoporous. Step uptake at ~35% RH. Water-stable. Used in AWH and adsorption cooling.",
    },
    {
        "name": "MIL-101(Cr)",
        "common_name": "Cr-MIL-101",
        "formula": "Cr3F(H2O)2O(BDC)3",
        "topology": "mtn",
        "metal_node": "Cr",
        "linker": "terephthalic acid (BDC)",
        "pore_limiting_diameter_A": 12.5,
        "largest_cavity_diameter_A": 34.0,
        "void_fraction": 0.84,
        "surface_area_m2_g": 3800.0,
        "surface_area_m2_cm3": 1800.0,
        "density_g_cm3": 0.44,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.10,
        "water_uptake_g_g_40rh": 0.65,
        "co2_uptake_mmol_g_015bar": 2.5,
        "co2_uptake_mmol_g_1bar": 16.0,
        "co2_n2_selectivity": 5.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.65,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Ferey et al., Science 2005; Loera-Serna et al., RSC Adv 2013",
        "core_mof_id": "OCUNAK",
        "notes": "Benchmark large-pore MOF. Highest BET SA in early MOF literature. Open Cr3+ sites. Water stable. Step uptake at 40% RH.",
    },
    {
        "name": "MIL-101(Cr)-NH2",
        "common_name": "Cr-MIL-101 amine",
        "formula": "Cr3F(H2O)2O(BDC-NH2)3",
        "topology": "mtn",
        "metal_node": "Cr",
        "linker": "2-aminoterephthalic acid",
        "pore_limiting_diameter_A": 10.8,
        "largest_cavity_diameter_A": 29.0,
        "void_fraction": 0.81,
        "surface_area_m2_g": 2900.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": True,
        "functional_groups": "-NH2",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.18,
        "water_uptake_g_g_40rh": 0.58,
        "co2_uptake_mmol_g_015bar": 3.5,
        "co2_uptake_mmol_g_1bar": 8.0,
        "co2_n2_selectivity": 40.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Bernt et al., Dalton Trans. 2011; Lin et al., ACS Appl Mater 2014",
        "core_mof_id": None,
        "notes": "Amine-functionalized MIL-101(Cr). Earlier step uptake than parent. Higher CO2/N2 selectivity due to -NH2 groups.",
    },
    {
        "name": "UiO-66",
        "common_name": "Zr-BDC",
        "formula": "Zr6O4(OH)4(BDC)6",
        "topology": "fcu",
        "metal_node": "Zr",
        "linker": "terephthalic acid (BDC)",
        "pore_limiting_diameter_A": 6.0,
        "largest_cavity_diameter_A": 11.2,
        "void_fraction": 0.49,
        "surface_area_m2_g": 1187.0,
        "surface_area_m2_cm3": 874.0,
        "density_g_cm3": 0.73,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.08,
        "water_uptake_g_g_40rh": 0.18,
        "co2_uptake_mmol_g_015bar": 1.0,
        "co2_uptake_mmol_g_1bar": 2.5,
        "co2_n2_selectivity": 18.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Cavka et al., JACS 2008; Hu et al., ChemSusChem 2014",
        "core_mof_id": "RUBTAK",
        "notes": "Exceptionally stable Zr-MOF. Benchmark for stability studies. Modest adsorption capacity.",
    },
    {
        "name": "UiO-66-NH2",
        "common_name": "Zr-BDC-NH2",
        "formula": "Zr6O4(OH)4(BDC-NH2)6",
        "topology": "fcu",
        "metal_node": "Zr",
        "linker": "2-aminoterephthalic acid",
        "pore_limiting_diameter_A": 6.0,
        "largest_cavity_diameter_A": 11.0,
        "void_fraction": 0.46,
        "surface_area_m2_g": 1020.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH,-NH2",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.12,
        "water_uptake_g_g_40rh": 0.25,
        "co2_uptake_mmol_g_015bar": 2.0,
        "co2_uptake_mmol_g_1bar": 4.0,
        "co2_n2_selectivity": 40.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Yang et al., RSC Adv 2012; McDonald et al., JACS 2015",
        "core_mof_id": None,
        "notes": "Amine-functionalized UiO-66. Chemisorbs CO2 via carbamate formation. Excellent stability.",
    },
    {
        "name": "CAU-10-H",
        "common_name": "Al-IPA",
        "formula": "Al(OH)(isophthalate)",
        "topology": None,
        "metal_node": "Al",
        "linker": "isophthalic acid",
        "pore_limiting_diameter_A": 3.7,
        "largest_cavity_diameter_A": 6.2,
        "void_fraction": 0.37,
        "surface_area_m2_g": 635.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.20,
        "water_uptake_g_g_40rh": 0.30,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Reinsch et al., CrystEngComm 2012; Henninger et al., Sol. Energy 2012",
        "core_mof_id": None,
        "notes": "Helical Al-MOF channels. Water stable. Step uptake at 20-30% RH. Investigated for AWH chiller cycles.",
    },
    {
        "name": "MIL-53(Al)",
        "common_name": "Al-BDC breathing MOF",
        "formula": "Al(OH)(BDC)",
        "topology": None,
        "metal_node": "Al",
        "linker": "terephthalic acid (BDC)",
        "pore_limiting_diameter_A": 8.5,
        "largest_cavity_diameter_A": 12.0,
        "void_fraction": 0.58,
        "surface_area_m2_g": 1370.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.98,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": 0.05,
        "water_uptake_g_g_40rh": 0.32,
        "co2_uptake_mmol_g_015bar": 1.2,
        "co2_uptake_mmol_g_1bar": 3.2,
        "co2_n2_selectivity": 30.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Loiseau et al., Chem. Eur. J. 2004; Bourrelly et al., JACS 2005",
        "core_mof_id": "FIQCEN",
        "notes": "Classic breathing MOF. Framework contracts/expands on adsorption. Good CO2 selectivity over N2.",
    },
    {
        "name": "DUT-4",
        "common_name": "Al-NDC",
        "formula": "Al(OH)(2,6-naphthalenedicarboxylate)",
        "topology": None,
        "metal_node": "Al",
        "linker": "2,6-naphthalenedicarboxylic acid",
        "pore_limiting_diameter_A": 7.9,
        "largest_cavity_diameter_A": 9.5,
        "void_fraction": 0.64,
        "surface_area_m2_g": 2163.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.22,
        "water_uptake_g_g_40rh": 0.48,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Senkovska et al., Microporous Mesoporous Mater. 2009",
        "core_mof_id": None,
        "notes": "Al-based, high-SA hydrophilic MOF with naphthalene linker. Water stable.",
    },
    {
        "name": "NU-1000",
        "common_name": "Zr-TBAPy",
        "formula": "Zr6(mu3-OH)8(OH)8(TBAPy)2",
        "topology": "csq",
        "metal_node": "Zr",
        "linker": "1,3,6,8-tetrakis(p-benzoate)pyrene",
        "pore_limiting_diameter_A": 8.8,
        "largest_cavity_diameter_A": 31.0,
        "void_fraction": 0.79,
        "surface_area_m2_g": 2320.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.35,
        "has_open_metal_sites": True,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.09,
        "water_uptake_g_g_40rh": 0.38,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Mondloch et al., JACS 2013",
        "core_mof_id": None,
        "notes": "Hierarchically porous Zr-MOF. Large mesopore channels useful for catalysis. Hydrophobic pyrene linker limits low-RH water uptake.",
    },

    # =========================================================================
    # CO2 CAPTURE
    # =========================================================================
    {
        "name": "Mg-MOF-74",
        "common_name": "Mg-dobdc / CPO-27-Mg",
        "formula": "Mg2(dobdc)",
        "topology": None,
        "metal_node": "Mg",
        "linker": "2,5-dioxido-1,4-benzenedicarboxylate (dobdc)",
        "pore_limiting_diameter_A": 11.0,
        "largest_cavity_diameter_A": 12.3,
        "void_fraction": 0.72,
        "surface_area_m2_g": 1542.0,
        "surface_area_m2_cm3": 837.0,
        "density_g_cm3": 0.90,
        "has_open_metal_sites": True,
        "functional_groups": "-OH",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 3.9,
        "co2_uptake_mmol_g_1bar": 8.1,
        "co2_n2_selectivity": 148.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Caskey et al., JACS 2008; McDonald et al., Nature 2015",
        "core_mof_id": "VOGTIV",
        "notes": "Benchmark CO2 sorbent. Highest CO2 uptake at 0.1-0.15 bar. Open Mg2+ sites. Degrades in liquid water — must be kept dry.",
    },
    {
        "name": "Ni-MOF-74",
        "common_name": "Ni-dobdc / CPO-27-Ni",
        "formula": "Ni2(dobdc)",
        "topology": None,
        "metal_node": "Ni",
        "linker": "dobdc",
        "pore_limiting_diameter_A": 11.0,
        "largest_cavity_diameter_A": 12.2,
        "void_fraction": 0.68,
        "surface_area_m2_g": 1350.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 1.19,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 3.5,
        "co2_uptake_mmol_g_1bar": 7.0,
        "co2_n2_selectivity": 65.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Dietzel et al., Chem Comm 2008; Caskey et al., JACS 2008",
        "core_mof_id": "LEJRIC",
        "notes": "Open Ni2+ sites with strong CO2 affinity. More water-stable than Mg-analog. Good for post-combustion capture.",
    },
    {
        "name": "Co-MOF-74",
        "common_name": "Co-dobdc / CPO-27-Co",
        "formula": "Co2(dobdc)",
        "topology": None,
        "metal_node": "Co",
        "linker": "dobdc",
        "pore_limiting_diameter_A": 11.0,
        "largest_cavity_diameter_A": 12.0,
        "void_fraction": 0.67,
        "surface_area_m2_g": 1341.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 1.24,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 3.7,
        "co2_uptake_mmol_g_1bar": 7.8,
        "co2_n2_selectivity": 80.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Dietzel et al., Angew. Chem. 2009",
        "core_mof_id": "LEJROG",
        "notes": "Co-MOF-74 isoreticular series. Open Co2+ sites. High CO2 selectivity over N2.",
    },
    {
        "name": "HKUST-1",
        "common_name": "Cu-BTC / MOF-199",
        "formula": "Cu3(BTC)2",
        "topology": "tbo",
        "metal_node": "Cu",
        "linker": "benzene-1,3,5-tricarboxylic acid (BTC / trimesate)",
        "pore_limiting_diameter_A": 9.0,
        "largest_cavity_diameter_A": 13.1,
        "void_fraction": 0.75,
        "surface_area_m2_g": 1850.0,
        "surface_area_m2_cm3": 1600.0,
        "density_g_cm3": 0.88,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 2.8,
        "co2_uptake_mmol_g_1bar": 5.0,
        "co2_n2_selectivity": 8.0,
        "ch4_uptake_cm3_cm3_35bar": 180.0,
        "ch4_uptake_cc_g_35bar": 210.0,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Chui et al., Science 1999; Farrusseng et al., JACS 2009",
        "core_mof_id": "FIQCEN01",
        "notes": "One of the most widely studied MOFs. Paddle-wheel Cu2 units. Open Cu sites. Degrades in humid air — not for water contact applications.",
    },
    {
        "name": "UiO-67",
        "common_name": "Zr-BPDC",
        "formula": "Zr6O4(OH)4(BPDC)6",
        "topology": "fcu",
        "metal_node": "Zr",
        "linker": "4,4'-biphenyldicarboxylic acid (BPDC)",
        "pore_limiting_diameter_A": 8.0,
        "largest_cavity_diameter_A": 16.0,
        "void_fraction": 0.65,
        "surface_area_m2_g": 2900.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.06,
        "water_uptake_g_g_40rh": 0.14,
        "co2_uptake_mmol_g_015bar": 0.8,
        "co2_uptake_mmol_g_1bar": 2.8,
        "co2_n2_selectivity": 12.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Valenzano et al., Chem. Mater. 2011",
        "core_mof_id": None,
        "notes": "Expanded UiO-66 with biphenyl linker. Larger pores but lower CO2 uptake per gram.",
    },
    {
        "name": "SIFSIX-3-Ni",
        "common_name": "KAUST-1",
        "formula": "Ni(pyrazine)2(SiF6)",
        "topology": None,
        "metal_node": "Ni",
        "linker": "pyrazine + hexafluorosilicate (SiF6)",
        "pore_limiting_diameter_A": 3.84,
        "largest_cavity_diameter_A": 4.65,
        "void_fraction": 0.30,
        "surface_area_m2_g": 368.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-F",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 1.6,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": 187.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Shekhah et al., Nature Communications 2014",
        "core_mof_id": None,
        "notes": "Exceptional CO2/N2 selectivity at dilute concentrations. Ultrasmall pores sized for CO2 (3.3 A kinetic diameter). KAUST group.",
    },
    {
        "name": "SIFSIX-3-Cu",
        "common_name": "KAUST-7",
        "formula": "Cu(pyrazine)2(SiF6)",
        "topology": None,
        "metal_node": "Cu",
        "linker": "pyrazine + hexafluorosilicate (SiF6)",
        "pore_limiting_diameter_A": 3.50,
        "largest_cavity_diameter_A": 4.15,
        "void_fraction": 0.27,
        "surface_area_m2_g": 300.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-F",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 1.24,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": 10000.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Bhatt et al., Nature Energy 2020",
        "core_mof_id": None,
        "notes": "Record CO2/N2 selectivity (>10000) at 400 ppm CO2. Designed for direct air capture. Fluorinated pore walls create optimal CO2 binding geometry.",
    },
    {
        "name": "ZIF-8",
        "common_name": "ZIF-8 / Basolite Z1200",
        "formula": "Zn(MeIm)2",
        "topology": "sod",
        "metal_node": "Zn",
        "linker": "2-methylimidazolate",
        "pore_limiting_diameter_A": 3.4,
        "largest_cavity_diameter_A": 11.6,
        "void_fraction": 0.47,
        "surface_area_m2_g": 1810.0,
        "surface_area_m2_cm3": 780.0,
        "density_g_cm3": 0.92,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.02,
        "water_uptake_g_g_40rh": 0.04,
        "co2_uptake_mmol_g_015bar": 0.4,
        "co2_uptake_mmol_g_1bar": 1.5,
        "co2_n2_selectivity": 5.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Park et al., PNAS 2006; Phan et al., Acc. Chem. Res. 2010",
        "core_mof_id": "VELVOY",
        "notes": "Zeolitic imidazolate framework. Exceptional chemical/thermal stability. Small aperture (3.4 A) selective for CO2 over larger molecules.",
    },
    {
        "name": "ZIF-67",
        "common_name": "Co-MeIm",
        "formula": "Co(MeIm)2",
        "topology": "sod",
        "metal_node": "Co",
        "linker": "2-methylimidazolate",
        "pore_limiting_diameter_A": 3.4,
        "largest_cavity_diameter_A": 11.6,
        "void_fraction": 0.46,
        "surface_area_m2_g": 1734.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.02,
        "water_uptake_g_g_40rh": 0.04,
        "co2_uptake_mmol_g_015bar": 0.45,
        "co2_uptake_mmol_g_1bar": 1.6,
        "co2_n2_selectivity": 5.5,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Park et al., PNAS 2006",
        "core_mof_id": None,
        "notes": "Co-based ZIF-8 isostructure. Slightly different pore chemistry. Cobalt sites offer marginal selectivity improvements.",
    },
    {
        "name": "MIL-125(Ti)-NH2",
        "common_name": "Ti-BDC-NH2",
        "formula": "Ti8O8(OH)4(BDC-NH2)6",
        "topology": None,
        "metal_node": "Ti",
        "linker": "2-aminoterephthalic acid",
        "pore_limiting_diameter_A": 5.5,
        "largest_cavity_diameter_A": 12.5,
        "void_fraction": 0.62,
        "surface_area_m2_g": 1400.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-NH2",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.15,
        "water_uptake_g_g_40rh": 0.35,
        "co2_uptake_mmol_g_015bar": 2.2,
        "co2_uptake_mmol_g_1bar": 5.5,
        "co2_n2_selectivity": 35.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Kim et al., Chem. Comm. 2012; Srinivas et al., ChemSusChem 2015",
        "core_mof_id": None,
        "notes": "Photoactive Ti-MOF with amine groups. Dual utility: CO2 capture and photocatalytic CO2 reduction.",
    },
    {
        "name": "bio-MOF-11",
        "common_name": "Zn-adeninate",
        "formula": "Zn8(ad)4(BPDC)6O2",
        "topology": None,
        "metal_node": "Zn",
        "linker": "adeninate + 4,4'-biphenyldicarboxylate",
        "pore_limiting_diameter_A": 4.0,
        "largest_cavity_diameter_A": 7.2,
        "void_fraction": 0.51,
        "surface_area_m2_g": 1148.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-NH2",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 2.5,
        "co2_uptake_mmol_g_1bar": 6.0,
        "co2_n2_selectivity": 75.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "An et al., JACS 2010",
        "core_mof_id": None,
        "notes": "Nucleobase-derived MOF. Amine groups from adenine create strong CO2 affinity. Among highest reported CO2/CH4 selectivities.",
    },
    {
        "name": "UTSA-16",
        "common_name": "Co-citrate MOF",
        "formula": "Co2K(citrate)2(H2O)2",
        "topology": None,
        "metal_node": "Co",
        "linker": "citric acid",
        "pore_limiting_diameter_A": 3.3,
        "largest_cavity_diameter_A": 5.0,
        "void_fraction": 0.32,
        "surface_area_m2_g": 628.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 3.3,
        "co2_uptake_mmol_g_1bar": 4.2,
        "co2_n2_selectivity": 315.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Xiang et al., Angew. Chem. 2012",
        "core_mof_id": None,
        "notes": "Exceptional CO2/N2 selectivity (315) with modest surface area. Pore aperture sized for CO2. Prepared from inexpensive citric acid.",
    },

    # =========================================================================
    # HYDROGEN STORAGE
    # =========================================================================
    {
        "name": "MOF-5",
        "common_name": "IRMOF-1 / Zn-BDC",
        "formula": "Zn4O(BDC)3",
        "topology": "pcu",
        "metal_node": "Zn",
        "linker": "terephthalic acid (BDC)",
        "pore_limiting_diameter_A": 8.0,
        "largest_cavity_diameter_A": 15.1,
        "void_fraction": 0.79,
        "surface_area_m2_g": 3534.0,
        "surface_area_m2_cm3": 1822.0,
        "density_g_cm3": 0.59,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 0.3,
        "co2_uptake_mmol_g_1bar": 1.8,
        "co2_n2_selectivity": 3.0,
        "ch4_uptake_cm3_cm3_35bar": 135.0,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.3,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Li et al., Nature 1999; Rowsell et al., JACS 2004",
        "core_mof_id": "SAHYIK",
        "notes": "First landmark high-SA MOF. Yaghi group. Prototype IRMOF series. Degrades in humid air (Zn-carboxylate bonds hydrolyze).",
    },
    {
        "name": "IRMOF-6",
        "common_name": "Zn-CDC MOF",
        "formula": "Zn4O(CDC)3",
        "topology": "pcu",
        "metal_node": "Zn",
        "linker": "1,2-dihydrocyclobutabenzene-3,6-dicarboxylate (CDC)",
        "pore_limiting_diameter_A": 9.8,
        "largest_cavity_diameter_A": 15.2,
        "void_fraction": 0.76,
        "surface_area_m2_g": 3263.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.65,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.5,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Rowsell et al., JACS 2004",
        "core_mof_id": None,
        "notes": "IRMOF series member. Slightly higher H2 uptake than MOF-5 due to cyclobutane ring. Unstable in moisture.",
    },
    {
        "name": "MOF-177",
        "common_name": "Zn-BTB",
        "formula": "Zn4O(BTB)2",
        "topology": "qom",
        "metal_node": "Zn",
        "linker": "4,4',4''-benzene-1,3,5-triyl-tribenzoate (BTB)",
        "pore_limiting_diameter_A": 10.8,
        "largest_cavity_diameter_A": 17.9,
        "void_fraction": 0.83,
        "surface_area_m2_g": 4500.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.43,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 0.2,
        "co2_uptake_mmol_g_1bar": 1.8,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.25,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Chae et al., Nature 2004; Furukawa et al., Science 2010",
        "core_mof_id": None,
        "notes": "Held BET surface area record at publication (~4500 m2/g). Triangular channel topology. Moisture-sensitive.",
    },
    {
        "name": "NU-100",
        "common_name": "Cu-TCEPB",
        "formula": "Cu3(TCEPB)2",
        "topology": "rht",
        "metal_node": "Cu",
        "linker": "5,5',5''-(((nitrilotris(ethane-2,1-diyl))tris(oxy))tris(ethane-2,1-diyl))triisophthalate (TCEPB)",
        "pore_limiting_diameter_A": 6.5,
        "largest_cavity_diameter_A": 30.0,
        "void_fraction": 0.90,
        "surface_area_m2_g": 6100.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.27,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 2.2,
        "h2_uptake_wt_100bar_77k": 9.95,
        "key_paper": "Farha et al., JACS 2010",
        "core_mof_id": None,
        "notes": "Record gravimetric H2 uptake at high pressure (9.95 wt% at 56 bar, 77 K). Open Cu2+ paddle-wheels. Exceptional BET SA (~6100 m2/g). Farha/Hupp group.",
    },
    {
        "name": "MOF-210",
        "common_name": "Zn-BTB/BPDC",
        "formula": "Zn4O(BTB)4/3(BPDC)",
        "topology": "toz",
        "metal_node": "Zn",
        "linker": "BTB + 4,4'-biphenyldicarboxylate (BPDC)",
        "pore_limiting_diameter_A": 13.3,
        "largest_cavity_diameter_A": 26.9,
        "void_fraction": 0.89,
        "surface_area_m2_g": 6240.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.25,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.5,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Furukawa et al., Science 2010",
        "core_mof_id": None,
        "notes": "Highest reported BET surface area at publication (~6240 m2/g). Ultra-low density (0.25 g/cm3). Moisture-sensitive Zn-carboxylate nodes.",
    },
    {
        "name": "PCN-68",
        "common_name": "Cu-PTEI",
        "formula": "Cu3(PTEI)2",
        "topology": "rht",
        "metal_node": "Cu",
        "linker": "5,5',5''-(((nitrilotris(ethane-2,1-diyl))tris(oxy))tris(benzene-4,1-diyl))triisophthalate (PTEI)",
        "pore_limiting_diameter_A": 7.8,
        "largest_cavity_diameter_A": 36.0,
        "void_fraction": 0.85,
        "surface_area_m2_g": 5109.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.38,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.87,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Yuan et al., Angew. Chem. 2010",
        "core_mof_id": None,
        "notes": "rht-type Cu-MOF with ultra-high SA. Open Cu paddle-wheel sites. High gravimetric H2 capacity.",
    },
    {
        "name": "NOTT-112",
        "common_name": "Cu-BHBT",
        "formula": "Cu3(BHBT)2",
        "topology": "rht",
        "metal_node": "Cu",
        "linker": "5,5',5''-benzene-1,3,5-triyl-tris(1-ethynyl-2-isophthalate) (BHBT)",
        "pore_limiting_diameter_A": 7.0,
        "largest_cavity_diameter_A": 25.0,
        "void_fraction": 0.78,
        "surface_area_m2_g": 3800.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.3,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Lin et al., JACS 2009",
        "core_mof_id": None,
        "notes": "Alkyne-decorated rht-type MOF. Triple bonds slightly increase H2 binding via pi interactions.",
    },
    {
        "name": "SNU-77H",
        "common_name": "Zn-BBAC",
        "formula": "Zn4O(BBAC)3",
        "topology": "pcu",
        "metal_node": "Zn",
        "linker": "4,4'-benzophenone-dicarboxylate (BBAC)",
        "pore_limiting_diameter_A": 11.0,
        "largest_cavity_diameter_A": 17.0,
        "void_fraction": 0.82,
        "surface_area_m2_g": 4030.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.49,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": 1.6,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Chun et al., JACS 2008",
        "core_mof_id": None,
        "notes": "High SA Zn-MOF with ketone functionality. Reported higher H2 isosteric heat than MOF-5.",
    },
    {
        "name": "Zn-MOF-74",
        "common_name": "Zn-dobdc / CPO-27-Zn",
        "formula": "Zn2(dobdc)",
        "topology": None,
        "metal_node": "Zn",
        "linker": "dobdc",
        "pore_limiting_diameter_A": 11.0,
        "largest_cavity_diameter_A": 12.0,
        "void_fraction": 0.69,
        "surface_area_m2_g": 1100.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 1.09,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 2.8,
        "co2_uptake_mmol_g_1bar": 5.9,
        "co2_n2_selectivity": 50.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Rosi et al., JACS 2005",
        "core_mof_id": None,
        "notes": "Open Zn2+ sites. Lower CO2 capacity than Mg-analog due to weaker metal-CO2 interaction. Moisture sensitive.",
    },

    # =========================================================================
    # METHANE / NATURAL GAS STORAGE
    # =========================================================================
    {
        "name": "PCN-14",
        "common_name": "Cu-NTBA",
        "formula": "Cu2(NTBA)",
        "topology": None,
        "metal_node": "Cu",
        "linker": "5,5'-(9,10-anthracenediyl)diisophthalate (NTBA)",
        "pore_limiting_diameter_A": 7.7,
        "largest_cavity_diameter_A": 14.5,
        "void_fraction": 0.77,
        "surface_area_m2_g": 1753.0,
        "surface_area_m2_cm3": 1253.0,
        "density_g_cm3": 0.76,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": 195.0,
        "ch4_uptake_cc_g_35bar": 260.0,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Ma et al., JACS 2008",
        "core_mof_id": None,
        "notes": "Held volumetric CH4 storage record at 290 K. Anthracene linker provides high CH4 binding enthalpy. Open Cu paddle-wheel sites.",
    },
    {
        "name": "NU-111",
        "common_name": "Cu-HHTP MOF",
        "formula": "Cu3(HHTP)2",
        "topology": "rht",
        "metal_node": "Cu",
        "linker": "5,5',5''-(((nitrilotris(ethane-2,1-diyl))tris(1H-1,2,3-triazole-4,1-diyl))tris(methylene))triisophthalate",
        "pore_limiting_diameter_A": 5.5,
        "largest_cavity_diameter_A": 24.0,
        "void_fraction": 0.83,
        "surface_area_m2_g": 4930.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.41,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": 196.0,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Peng et al., Angew. Chem. 2013",
        "core_mof_id": None,
        "notes": "rht-type Cu-MOF. High methane uptake with good deliverable capacity. Open Cu sites provide CH4 binding affinity.",
    },
    {
        "name": "MOF-519",
        "common_name": "Al-BTB-formate",
        "formula": "Al8(BTB)4(formate)8",
        "topology": None,
        "metal_node": "Al",
        "linker": "BTB + formate",
        "pore_limiting_diameter_A": 7.6,
        "largest_cavity_diameter_A": 12.3,
        "void_fraction": 0.69,
        "surface_area_m2_g": 2400.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.60,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": 195.0,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Mason et al., JACS 2015",
        "core_mof_id": None,
        "notes": "Near DoE volumetric CH4 target (259 cm3/cm3 at 65 bar). Al-based for stability. Dense packing approach.",
    },
    {
        "name": "UTSA-20",
        "common_name": "Cu-TPBTM",
        "formula": "Cu3(TPBTM)2",
        "topology": "tbo",
        "metal_node": "Cu",
        "linker": "5,5',5''-[1,3,5-benzenetriyltris(carbonylimino)]tris[1,3-benzenedicarboxylate] (TPBTM)",
        "pore_limiting_diameter_A": 8.2,
        "largest_cavity_diameter_A": 13.5,
        "void_fraction": 0.73,
        "surface_area_m2_g": 2210.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.78,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": 175.0,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Guo et al., Angew. Chem. 2011",
        "core_mof_id": None,
        "notes": "Amide-decorated Cu-MOF. CH4 uptake competitive with HKUST-1. Open Cu sites and amide-CH4 interactions.",
    },
    {
        "name": "PCN-11",
        "common_name": "Cu-SBTC",
        "formula": "Cu2(SBTC)",
        "topology": None,
        "metal_node": "Cu",
        "linker": "trans-4,4'-stilbenedicarboxylate (SBTC)",
        "pore_limiting_diameter_A": 9.2,
        "largest_cavity_diameter_A": 16.0,
        "void_fraction": 0.74,
        "surface_area_m2_g": 1931.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": 165.0,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Wang et al., JACS 2008",
        "core_mof_id": None,
        "notes": "Paddle-wheel Cu-MOF with stilbene linker. Good CH4 capacity and deliverable ratio.",
    },
    {
        "name": "NOTT-101",
        "common_name": "Cu-BPTC",
        "formula": "Cu2(BPTC)",
        "topology": None,
        "metal_node": "Cu",
        "linker": "biphenyl-3,3',5,5'-tetracarboxylate (BPTC)",
        "pore_limiting_diameter_A": 7.8,
        "largest_cavity_diameter_A": 12.0,
        "void_fraction": 0.72,
        "surface_area_m2_g": 2316.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.74,
        "has_open_metal_sites": True,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": 170.0,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Lin et al., JACS 2009",
        "core_mof_id": None,
        "notes": "Cu paddle-wheel with biphenyl tetracarboxylate. NOTT series (Nottingham group). Competitive CH4 capacity.",
    },

    # =========================================================================
    # VOC REMOVAL / AIR PURIFICATION (structural proxy scoring)
    # =========================================================================
    {
        "name": "MIL-47(V)",
        "common_name": "V-BDC breathing MOF",
        "formula": "V(O)(BDC)",
        "topology": None,
        "metal_node": "V",
        "linker": "terephthalic acid (BDC)",
        "pore_limiting_diameter_A": 8.5,
        "largest_cavity_diameter_A": 11.8,
        "void_fraction": 0.63,
        "surface_area_m2_g": 1200.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 1.00,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "high",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Barthelet et al., Angew. Chem. 2002; Alaerts et al., JACS 2008",
        "core_mof_id": None,
        "notes": "Vanadyl chains with BDC. Rigid (non-breathing in dry gas). Excellent toluene/benzene adsorption. Hydrophobic pores. Water stable.",
    },
    {
        "name": "IRMOF-8",
        "common_name": "Zn-NDC",
        "formula": "Zn4O(NDC)3",
        "topology": "pcu",
        "metal_node": "Zn",
        "linker": "2,6-naphthalenedicarboxylic acid (NDC)",
        "pore_limiting_diameter_A": 12.5,
        "largest_cavity_diameter_A": 18.4,
        "void_fraction": 0.83,
        "surface_area_m2_g": 4462.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.41,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "low",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Eddaoudi et al., Science 2002",
        "core_mof_id": None,
        "notes": "Very high SA IRMOF. Naphthalene linker enables pi-pi stacking interactions with aromatic VOCs. Moisture-sensitive.",
    },
    {
        "name": "ZIF-90",
        "common_name": "Zn-ICA (aldehyde-ZIF)",
        "formula": "Zn(ICA)2",
        "topology": "sod",
        "metal_node": "Zn",
        "linker": "imidazolate-2-carboxaldehyde (ICA)",
        "pore_limiting_diameter_A": 3.5,
        "largest_cavity_diameter_A": 11.2,
        "void_fraction": 0.45,
        "surface_area_m2_g": 1270.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "high",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": 0.6,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Morris et al., JACS 2008",
        "core_mof_id": None,
        "notes": "Aldehyde-functionalized ZIF. Post-synthetic modification capability. Good for formaldehyde adsorption.",
    },
    {
        "name": "DMOF-1",
        "common_name": "Zn-BDC-DABCO",
        "formula": "Zn2(BDC)2(DABCO)",
        "topology": "pcu",
        "metal_node": "Zn",
        "linker": "terephthalic acid (BDC) + 1,4-diazabicyclo[2.2.2]octane (DABCO)",
        "pore_limiting_diameter_A": 7.5,
        "largest_cavity_diameter_A": 9.2,
        "void_fraction": 0.67,
        "surface_area_m2_g": 2500.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": None,
        "has_open_metal_sites": False,
        "functional_groups": "",
        "water_stability": "moderate",
        "water_uptake_g_g_20rh": None,
        "water_uptake_g_g_40rh": None,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Dybtsev et al., Angew. Chem. 2004",
        "core_mof_id": None,
        "notes": "Pillared-layer MOF. Tunable pore size by linker swapping. Good toluene uptake. Breathing behavior in some analogs.",
    },
    {
        "name": "MIL-101(Al)",
        "common_name": "Al-MIL-101",
        "formula": "Al3F(H2O)2O(BDC)3",
        "topology": "mtn",
        "metal_node": "Al",
        "linker": "terephthalic acid (BDC)",
        "pore_limiting_diameter_A": 12.2,
        "largest_cavity_diameter_A": 33.0,
        "void_fraction": 0.83,
        "surface_area_m2_g": 3100.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.45,
        "has_open_metal_sites": True,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.08,
        "water_uptake_g_g_40rh": 0.52,
        "co2_uptake_mmol_g_015bar": 1.8,
        "co2_uptake_mmol_g_1bar": 9.5,
        "co2_n2_selectivity": 6.0,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Loiseau et al., Chem. Mater. 2015; Yang et al., RSC Adv. 2012",
        "core_mof_id": None,
        "notes": "Al-based MIL-101 analog. Water stable (unlike Cr). High SA. Large mesopores effective for VOC removal from air streams.",
    },
    {
        "name": "MIL-68(Al)",
        "common_name": "Al-MIL-68",
        "formula": "Al(OH)(BDC)",
        "topology": None,
        "metal_node": "Al",
        "linker": "terephthalic acid (BDC)",
        "pore_limiting_diameter_A": 6.4,
        "largest_cavity_diameter_A": 16.0,
        "void_fraction": 0.58,
        "surface_area_m2_g": 1100.0,
        "surface_area_m2_cm3": None,
        "density_g_cm3": 0.91,
        "has_open_metal_sites": False,
        "functional_groups": "-OH",
        "water_stability": "high",
        "water_uptake_g_g_20rh": 0.07,
        "water_uptake_g_g_40rh": 0.25,
        "co2_uptake_mmol_g_015bar": None,
        "co2_uptake_mmol_g_1bar": None,
        "co2_n2_selectivity": None,
        "ch4_uptake_cm3_cm3_35bar": None,
        "ch4_uptake_cc_g_35bar": None,
        "h2_uptake_wt_1bar_77k": None,
        "h2_uptake_wt_100bar_77k": None,
        "key_paper": "Loiseau et al., Chem. Eur. J. 2006",
        "core_mof_id": None,
        "notes": "Honeycomb-topology Al-MOF with triangular and hexagonal channels. Water stable. VOC removal applications.",
    },
]
# fmt: on


def load_seed_data(db: Session) -> None:
    from sqlalchemy import func, select
    count = db.execute(select(func.count()).select_from(MOFStructure)).scalar()
    if count and count > 0:
        return
    for entry in SEED_MOFS:
        db.add(MOFStructure(**entry))
    db.commit()
